//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 04:09:11 PM WEST 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="countryname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="medals">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="athletename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="medaltype">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="Gold"/>
 *                                             &lt;enumeration value="Silver"/>
 *                                             &lt;enumeration value="Bronze"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country"
})
@XmlRootElement(name = "countries")
public class Countries {

    protected List<Countries.Country> country;

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Countries.Country }
     * 
     * 
     */
    public List<Countries.Country> getCountry() {
        if (country == null) {
            country = new ArrayList<Countries.Country>();
        }
        return this.country;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="countryname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="medals">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="athletename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="medaltype">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="Gold"/>
     *                                   &lt;enumeration value="Silver"/>
     *                                   &lt;enumeration value="Bronze"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countryname",
        "countrycode",
        "medals"
    })
    public static class Country {

        @XmlElement(required = true)
        protected String countryname;
        @XmlElement(required = true)
        protected String countrycode;
        @XmlElement(required = true)
        protected Countries.Country.Medals medals;

        public String toString(){
            return countryname+"("+countrycode+")";
        }

        /**
         * Gets the value of the countryname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryname() {
            return countryname;
        }

        /**
         * Sets the value of the countryname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryname(String value) {
            this.countryname = value;
        }

        /**
         * Gets the value of the countrycode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountrycode() {
            return countrycode;
        }

        /**
         * Sets the value of the countrycode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountrycode(String value) {
            this.countrycode = value;
        }

        /**
         * Gets the value of the medals property.
         * 
         * @return
         *     possible object is
         *     {@link Countries.Country.Medals }
         *     
         */
        public Countries.Country.Medals getMedals() {
            return medals;
        }

        /**
         * Sets the value of the medals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Countries.Country.Medals }
         *     
         */
        public void setMedals(Countries.Country.Medals value) {
            this.medals = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="athletename" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="medaltype">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="Gold"/>
         *                         &lt;enumeration value="Silver"/>
         *                         &lt;enumeration value="Bronze"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "medal"
        })
        public static class Medals {

            protected List<Countries.Country.Medals.Medal> medal;

            /**
             * Gets the value of the medal property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the medal property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMedal().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Countries.Country.Medals.Medal }
             * 
             * 
             */
            public List<Countries.Country.Medals.Medal> getMedal() {
                if (medal == null) {
                    medal = new ArrayList<Countries.Country.Medals.Medal>();
                }
                return this.medal;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="athletename" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="medaltype">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="Gold"/>
             *               &lt;enumeration value="Silver"/>
             *               &lt;enumeration value="Bronze"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "athletename",
                "medaltype",
                "sport",
                "category"
            })
            public static class Medal {

                @XmlElement(required = true)
                protected String athletename;
                @XmlElement(required = true)
                protected String medaltype;
                @XmlElement(required = true)
                protected String sport;
                @XmlElement(required = true)
                protected String category;


                public String toString(){
                    String res="";

                    res+="type:"+medaltype+"\n";
                    res+="athlete/team name:"+athletename+"\n";
                    res+="sport:"+sport+"\n";
                    res+="category:"+category;

                    return res;
                }

                /**
                 * Gets the value of the athletename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAthletename() {
                    return athletename;
                }

                /**
                 * Sets the value of the athletename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAthletename(String value) {
                    this.athletename = value;
                }

                /**
                 * Gets the value of the medaltype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMedaltype() {
                    return medaltype;
                }

                /**
                 * Sets the value of the medaltype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMedaltype(String value) {
                    this.medaltype = value;
                }

                /**
                 * Gets the value of the sport property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSport() {
                    return sport;
                }

                /**
                 * Sets the value of the sport property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSport(String value) {
                    this.sport = value;
                }

                /**
                 * Gets the value of the category property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategory() {
                    return category;
                }

                /**
                 * Sets the value of the category property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategory(String value) {
                    this.category = value;
                }

            }

        }

    }

}
